version: '2'
services:
    jhipstersampleapplication51-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleApplication51/mongodb/:/data/db/
